server:
  port: 8001
  

spring:
   application: 
    name:  microservicecloud-provider-8001 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址     
 


